import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import AnsButton from "../components/AnsButton";
import Question from "../components/Question";
import Test from "../components/Test";
import styles from "../styles/Home.module.css";
import { generateQuestions, Question as Q } from "../util";

type Props = {
  questions: Q[];
};
const Under10Page: NextPage<Props> = ({ questions }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Test {...{ questions }} />
      </main>
    </div>
  );
};

export default Under10Page;

export const getServerSideProps = () => {
  const questions = generateQuestions(90, 20);

  return {
    props: {
      questions,
    },
  };
};
